import type { ThemeId } from '@tentaclaire/shared';
import type { ThemeManifest } from './types.js';

export const DEFAULT_THEME_ID: ThemeId = 'maraudeur';

export const THEMES: Record<ThemeId, ThemeManifest> = {
  maraudeur: {
    id: 'maraudeur',
    label: 'Carte du Maraudeur',
    colors: {
      background: '#e8d5a9',
      fogFill: '#e0c98f',
      fogFillSecondary: '#d6bc7d',
      grid: 'rgba(59, 42, 26, 0.35)',
      characterFill: '#3b2a1a',
      characterAccent: '#e8d5a9',
      torchFlame: '#8b2f2f',
      ghostFill: 'rgba(59, 42, 26, 0.45)',
      ghostAccent: '#3b2a1a',
    },
    fontDisplay: "'IM Fell English', 'Caudex', serif",
    fontBody: "'Caudex', serif",
    fogStyle: 'parchment',
    gridStyle: 'irregular-ink',
    ghostShape: 'sketch',
    characterLineStyle: 'sketchy',
    revealEffect: 'fade',
    hasFootprintTrail: true,
  },
  manoir: {
    id: 'manoir',
    label: 'Manoir hanté',
    colors: {
      background: '#2a1a3a',
      fogFill: '#251733',
      fogFillSecondary: '#2e1c3f',
      grid: 'rgba(201, 168, 76, 0.25)',
      characterFill: '#c9a84c',
      characterAccent: '#2a1a3a',
      torchFlame: '#7da87b',
      ghostFill: 'rgba(255, 255, 255, 0.85)',
      ghostAccent: '#2a1a3a',
    },
    fontDisplay: "'Playfair Display', serif",
    fontBody: "'Playfair Display', serif",
    fogStyle: 'damask',
    gridStyle: 'thin-gold',
    ghostShape: 'sheet',
    characterLineStyle: 'plain',
    revealEffect: 'fade',
    hasFootprintTrail: false,
  },
  halloween: {
    id: 'halloween',
    label: 'Halloween',
    colors: {
      background: '#1a1a1a',
      fogFill: '#181818',
      fogFillSecondary: '#1f1f1f',
      grid: 'rgba(242, 140, 40, 0.4)',
      characterFill: '#f28c28',
      characterAccent: '#1a1a1a',
      torchFlame: '#f28c28',
      ghostFill: 'rgba(106, 61, 154, 0.9)',
      ghostAccent: '#f2e6ff',
    },
    fontDisplay: "'Creepster', cursive",
    fontBody: "system-ui, sans-serif",
    fogStyle: 'cartoon',
    gridStyle: 'cartoon-wavy',
    ghostShape: 'kawaii',
    characterLineStyle: 'plain',
    revealEffect: 'fade',
    hasFootprintTrail: false,
  },
  cimetiere: {
    id: 'cimetiere',
    label: 'Cimetière',
    colors: {
      background: '#0e1a2b',
      fogFill: '#0c1826',
      fogFillSecondary: '#9fb4c7',
      grid: 'rgba(159, 180, 199, 0.2)',
      characterFill: '#e8ecf1',
      characterAccent: '#0e1a2b',
      torchFlame: '#e8ecf1',
      ghostFill: 'rgba(159, 180, 199, 0.5)',
      ghostAccent: '#e8ecf1',
    },
    fontDisplay: "'Cormorant', serif",
    fontBody: "'Cormorant', serif",
    fogStyle: 'drift',
    gridStyle: 'thin-cold',
    ghostShape: 'spectre',
    characterLineStyle: 'plain',
    revealEffect: 'fade',
    hasFootprintTrail: false,
  },
  neon: {
    id: 'neon',
    label: 'Néon',
    colors: {
      background: '#0a0a0f',
      fogFill: '#0a0a0f',
      fogFillSecondary: '#111018',
      grid: '#b026ff',
      characterFill: '#0a0a0f',
      characterAccent: '#26f7ff',
      torchFlame: '#ff2688',
      ghostFill: '#0a0a0f',
      ghostAccent: '#b026ff',
    },
    fontDisplay: "'Press Start 2P', monospace",
    fontBody: "system-ui, sans-serif",
    fogStyle: 'neon',
    gridStyle: 'neon-glow',
    ghostShape: 'neon-outline',
    characterLineStyle: 'glow',
    revealEffect: 'flash',
    hasFootprintTrail: false,
  },
};
